services:

  grafana:
    container_name: agraf
    image: grafana/grafana:latest
    environment:
    - GF_PANELS_DISABLE_SANITIZE_HTML=true
    - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=scylladb-scylla-datasource
    - GF_AUTH_BASIC_ENABLED=true
    - GF_AUTH_ANONYMOUS_ENABLED=false
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_ANALYTICS_REPORTING_ENABLED=false
    - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
    - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
    - GF_SERVER_ENABLE_GZIP=false
    - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/ver_5.4/scylla-overview.5.4.json

    ports:
    - 3001:3000
    user: 1000:1000
    volumes:
    - ./grafana/build:/var/lib/grafana/dashboards
    - ./grafana/plugins:/var/lib/grafana/plugins
    - ./grafana/provisioning:/var/lib/grafana/provisioning
    - ./grafana/data:/var/lib/grafana/data
    - ./grafana/data/grafana.db:/var/lib/grafana/grafana.db
    networks:
      - stock-network

  prometheus:
    container_name: aprom
    image: prom/prometheus:latest
    ports:
    - 9091:9090
    volumes:
    - ./prometheus/build/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/prom_rules/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
    - ./prometheus/prom_rules:/etc/prometheus/prom_rules
    - ./prometheus/targets/scylla_servers.yml:/etc/scylla.d/prometheus/targets/scylla_servers.yml
    - ./prometheus/targets/node_exporter_servers.yml:/etc/scylla.d/prometheus/targets/node_exporter_servers.yml
    - prometheus_data:/prometheus
    networks:
    - stock-network

  alertmanager:
    container_name: aalert
    image: prom/alertmanager:latest
    ports:
    - 9093:9093
    volumes:
    - ./prometheus/alertmanager.yml:/etc/alertmanager/config.yml
    command:
    - --config.file=/etc/alertmanager/config.yml
    networks:
    - stock-network

  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    command:
    - --config.file=/mnt/config/loki-config.yaml
    ports:
    - 3100:3100
    volumes:
    - ./loki/rules:/etc/loki/rules/fake:z
    - ./loki/conf:/mnt/config:z
    - loki_wal:/wal:z
    - loki_data:/tmp/loki
    networks:
    - stock-network

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    command:
    - --config.file=/etc/promtail/config.yml
    ports:
    - 1514:1514
    - 9080:9080
    volumes:
    - ./loki/promtail/promtail_config.compose.yml:/etc/promtail/config.yml
    networks:
    - stock-network

volumes:
  prometheus_data:
  loki_wal:
  loki_data:

networks:
  stock-network:
    name: stock-network
    external: true
